### ISSUE TITLE
`--cpu-bind=none` needed to avoid wrong pinning effect

### ISSUE THREAD

**Issue by jhgoebbert** [mathworks/matlab-parallel-slurm-plugin#5]
Hi everyone,

the SMPD daemon (`mw_smpd`) gets started on each compute node once by the system's `srun` here:
https://github.com/mathworks/matlab-parallel-slurm-plugin/blob/main/communicatingJobWrapperSmpd.sh#L177

This SMPD daemon then is eventually the parent of each MPI task.
Hence, each MPI task will inherit the pinning option of the SMPD daemon.

If the system's SLURM is configured to set a default pinning which pins each task to a core
then the SMPD daemon and all its child processes will be pinned to a single core like this

![65f7ff32-aecf-4a82-908e-d463576927a4](https://github.com/user-attachments/assets/9a1f39e0-28c3-40ca-bab5-08dc64838495)

Therefore I recommend to include a `--cpu-bind=none` as an argument of `srun`.  
This results than in a much better use of the compute resources:
![99ca8839-288f-4d53-99c6-15395dc3e25e](https://github.com/user-attachments/assets/8c91986a-fa7b-44bf-be85-bada774fadd9)

**Comment by jmcave** [comment]
Thanks for reporting! Verified this behaviour internally with Slurm configuration:
```
TaskPlugin=task/affinity
TaskPluginParam=cores
```
Have added `--cpu-bind=none` into calls to `srun` as suggested.
